-- ITEM_TREE가 NULL이면 ROOT

-- LEAF NODE를 찾아야함

SELECT DISTINCT b.ITEM_ID, a.ITEM_NAME, a.RARITY 
FROM ITEM_INFO AS a
JOIN ITEM_TREE AS b
ON a.ITEM_ID = b.ITEM_ID
WHERE  b.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
    )
ORDER BY b.ITEM_ID DESC;


