-- 260407 
-- 2022-03월의 판매날짜, 상품ID, 유저ID, 판매량 출력 
-- OFFLINE_SALIE 테이블 판매 데이터 USER_ID null이니까 RIGHT JOIN? 
-- 결과 판매일 기준 오름차순, 상품 ID 오름차순, 유저ID 오름차순 

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE SALES_DATE LIKE '2022-03%'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT 
FROM OFFLINE_SALE 
WHERE SALES_DATE LIKE '2022-03%'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
