-- 코드를 입력하세요


-- 1. 생산일자 2022-05
-- 2. 총매출 기준 내림차순 - 식품 ID 오름차순
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT as A
JOIN FOOD_ORDER as B ON B.PRODUCE_DATE LIKE '2022-05%'
and A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;