-- 260407 리뷰를 가장 많이 작성한 회원들의 리뷰 조회 
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일 
-- 리뷰 작성일 기준 오름차순 - 리뷰 텍스트 기준 오름차순 

SELECT M.MEMBER_NAME AS MEMBER_NAME, R.REVIEW_TEXT AS REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M JOIN REST_REVIEW AS R 
ON M.MEMBER_ID = R.MEMBER_ID 
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC 
    LIMIT 1
)
ORDER BY R.REVIEW_DATE ASC , R.REVIEW_TEXT ASC;

