-- YEAR, YEAR_DEV, ID 
-- 편차는 연도별로 가장 큰 대장균의 크기 - 각 대장균의 크기 
-- 연도 오름차순 대장균 편차 오름차순 

SELECT YEAR(e.DIFFERENTIATION_DATE) AS YEAR, 
(SELECT MAX(e2.SIZE_OF_COLONY) FROM ECOLI_DATA e2 
 WHERE YEAR(e2.DIFFERENTIATION_DATE) = YEAR(e.DIFFERENTIATION_DATE)) - e.SIZE_OF_COLONY AS YEAR_DEV, 
ID
FROM ECOLI_DATA e
ORDER BY YEAR, YEAR_DEV;